### ISSUE TITLE
parallax

### ISSUE THREAD

**Issue by vivkay** [vivkay/pointer#5]
Hi @thomasjbradley!

I want to add parallax to my site (I'm pulling out all the bells and whistles to use this site for a portfolio piece and to practice, practice, practice!!)

I noticed in your tutorial you used an < img > tag for your billboard. Mine is currently in CSS like this:

```
.billboard {
  overflow: hidden;
  background-image: url(../img/billboard-pointer.jpg);
  background-repeat: no-repeat;
  background-position: center center;
  background-size: cover;
  padding: 5em;
  width: 100%;
}
```

Before I go down the path of parallax, I wanted to check that I can still do your technique with a CSS background image?

Also, in general, I am a little confused about the benefits of either way. Specifically, does it matter if I use the < img > tag in HTML for my billboard (or 'hero banner'), and when is a CSS styled background image an advantage?

THANKS!!!

(hope your summer is awesome so far!)

V

**Comment by thomasjbradley** [comment]
From a parallax point of view it probably doesn't matter whether it’s a background image or not, but what matters is that there are the correct amount of elements. I’m using an `<img>` tag because I want it to travel at a different speed. If you want to use a background image then you’d likely need and empty div to make it work, like: 

``` html
<header>
  <div class="billboard"></div>
  <div>
    <h1>…</h1>
  </div>
</header>
```

The choice about using an `<img>` vs. a background image is purely a semantics choice: is the image an important part of the content or just decoration?

**Comment by vivkay** [comment]
Awesome -thanks for the clarification!!
